### ISSUE TITLE
Python Dev?

### ISSUE THREAD

**Issue by preritdas** [blairnangle/python3-numpy-ta-lib#1]
This is more of a question. I've never been able to install TA-Lib on Linux without first installing and configuring `python-dev`/`python3-dev`/`python3.10-dev`. Is there a reason you haven't done so in your Dockerfile?

**Comment by blairnangle** [comment]
Not that I'm aware of! Can you describe to me what `python-dev` does?

**Comment by preritdas** [comment]
Interesting… `python3-dev` allows Python to build and utilize C extensions and headers, ex. when you have `#include <Python.h>` in an extension’s headers. I’ve found that whenever I try to install TA-Lib without `python-dev` I’m greeted with an error at the pip build stage saying it doesn’t know how to handle that C line.
